### ISSUE TITLE
`SlashCommandEvent` triggered by DM channel cause Fatal error

### ISSUE THREAD

**Issue by frank89722** [SketchMaster2001/Swiftcord#14]
As title 

`Swiftcord/SlashCommandEvent.swift:55: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

**Comment by SketchMaster2001** [comment]
I assume this is because Discord does not send the `member` field in the JSON payload. I will need to check if it exists then try and parse. Thank you for bringing this to my attention!

**Comment by SketchMaster2001** [comment]
Fixed in c6c5d2c
